default: &default
  adapter: postgresql
  encoding: utf-8
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: elearnio_coding_challenge_development

test:
  <<: *default
  database: elearnio_coding_challenge_test

production:
  <<: *default
  database: elearnio_coding_challenge_production
